Content for introduction page
prometheus-operator/website pull request #88
Opened 2024-07-09 05:19 UTC by AshwinSriram11

According to #82, this PR has modified the Introduction page.

2024-07-09 19:42 UTC, nicolastakashi approved these changes

2024-07-11 18:09 UTC, ArthurSens reviewed
Good start! I just have one comment about the goals

2024-07-11 18:09 UTC, ArthurSens commented on content/docs/getting-started/introduction.md
> +- Automate the management of Prometheus monitoring targets, ultimately increasing efficiency.
We care about other things as well! I'm not sure how to fit all into bullet points (maybe we could do a mixture of text+bullet points?)

But we want to abstract the complexity of scalability in many different layers:
* Storage - Prometheus can be deployed with low retention periods and deployed with Thanos Sidecars[[1](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ThanosSpec)][[2](https://thanos.io/v0.4/components/sidecar/)] if you have a long term storage for your metrics. This helps with Prometheus scalability because keeping storage low makes it easier to deploy more prometheuses.
* Rule Evaluation - We offer ThanosRuler with similar purposes as above.
* Scraping/Storage - We've recently added features that integrate well with [HPAs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/), to ensure new instances are automatically created when load increases, and equally deleted when load decreases.


We abstract configuration validation:
* AlertmanagerConfig was created so we could use k8s admission webhooks to fail early when invalid configuration is provided.
* Prometheus rules also go through similar validations
* We're evaluating using [CEL](https://kubernetes.io/docs/reference/using-api/cel/) to make sure mutually exclusive configurations aren't set by accident.

Abstract configuration complexity:
* ServiceMonitor/PodMonitor/Probes abstract [Prometheus relabeling rules](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config), using K8s "simpler language". Instead of learning relabeling rules, once can just understand label selectors and the Operator will make sure the correct targets are configured for scraping.

2024-07-11 18:09 UTC, ArthurSens commented on content/docs/getting-started/introduction.md
> +- Automate the management of Prometheus monitoring targets, ultimately increasing efficiency.
With that said, I agree this is too much information to put on the page, but maybe we can abstract the comment above in a small text+bullet points? 😛

2024-07-11 18:11 UTC, ArthurSens commented
And now that I've realized we have markdown files and link in this repository, maybe we could add [mdox](https://github.com/bwplotka/mdox) to the CI of this repo? Similar to what we do on prometheus-operator

2024-07-12 16:57 UTC, AshwinSriram11 commented on content/docs/getting-started/introduction.md
> +
I wanted to add more points in the next commit.

2024-07-12 17:01 UTC, AshwinSriram11 commented on content/docs/getting-started/introduction.md
> +- Automate the management of Prometheus monitoring targets, ultimately increasing efficiency.
I agree with all this. still this would be way too much information on the introduction page. Let me try to compress the info and add to the page

2024-07-13 11:40 UTC, AshwinSriram11 commented on content/docs/getting-started/introduction.md
> +- The Operator abstracts the complexity of many aspects in management of Prometheus resources. Let us look into each of them:
I have added the points @ArthurSens mentioned as sub-points to abstraction of complexity.  Wdyt?

2024-07-17 18:34 UTC, ArthurSens requested changes
Sorry if my previous comments misled you. I think there's too much information now 😅 

While before the only 2 bullet points were too few, now we're going too deep into implementation details with the new points.

Let's see...
Maybe **Configuration** and **Configuration Validation** could be merged into one single thing? Maybe **Configuration Abstraction and Validation**? We don't need to mention that validation is done via Admission webhooks and mentioning CEL is definitely too much. I know I mentioned them in the previous comment but I just wanted to give you context, adding them here is implementation detail.

Regarding the other three, maybe this could be just one: **Scalability**. Mentioning that we offer scalability-related features in many parts of the monitoring stack: rule evaluation, scrape target sharding, querying, etc

2024-07-22 09:19 UTC, AshwinSriram11 commented
>  Sorry if my previous comments misled you. I think there's too much information now 😅

I actually understood what you meant but I thought that summarising all the points first would and then narrowing it down would be better.

2024-07-22 12:38 UTC, ArthurSens approved these changes
LGTM!

2024-07-22 12:38 UTC, ArthurSens commented on content/docs/getting-started/introduction.md
> +- **Scaling** - There are many scaling-related features provided by the Operator like [ThanosRuler](https://prometheus-operator.dev/docs/platform/thanos/#thanos-ruler) custom resource for rule evalua
```suggestion
- **Scaling** - There are many scaling-related features provided by the Operator like [ThanosRuler](https://prometheus-operator.dev/docs/platform/thanos/#thanos-ruler) custom resource for rule evaluation, workload distribution across multiple Prometheus instances using scrape target sharding, and running [Thanos sidecar](https://thanos.io/v0.4/components/sidecar/) in Prometheus instance for long-term storage.
```

small typo :P

2024-07-22 12:46 UTC, merged